/**
 * Firebase Storage Utilities
 * Handles image upload and deletion in Firebase Cloud Storage
 */

import { storage } from '../firebase';
import { ref, uploadBytes, getDownloadURL, deleteObject } from 'firebase/storage';

/**
 * Generate a unique filename for recipe images
 * @param {File} file - The file to generate a name for
 * @returns {string} Unique filename with timestamp and random string
 */
function generateUniqueFilename(file) {
  const timestamp = Date.now();
  const randomStr = Math.random().toString(36).substring(2, 15);
  
  // Map MIME type to extension to avoid trusting user-provided filename
  const extensionMap = {
    'image/jpeg': 'jpg',
    'image/jpg': 'jpg',
    'image/png': 'png',
    'image/gif': 'gif',
    'image/webp': 'webp'
  };
  
  const extension = extensionMap[file.type] || 'jpg';
  return `${timestamp}-${randomStr}.${extension}`;
}

/**
 * Upload a recipe image to Firebase Storage
 * @param {File} file - The image file to upload
 * @returns {Promise<string>} - Download URL of the uploaded image
 */
export async function uploadRecipeImage(file) {
  if (!file) {
    throw new Error('No file provided');
  }

  // Validate file size (limit to 5MB)
  const maxSize = 5 * 1024 * 1024; // 5MB
  if (file.size > maxSize) {
    throw new Error('Image file size must be less than 5MB');
  }

  // Validate file type
  const validTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif', 'image/webp'];
  if (!validTypes.includes(file.type)) {
    throw new Error('Invalid file type. Please upload a JPEG, PNG, GIF, or WebP image');
  }

  try {
    // Generate unique filename
    const filename = generateUniqueFilename(file);
    
    // Create a reference to the storage location
    const storageRef = ref(storage, `recipes/${filename}`);
    
    // Upload the file
    const snapshot = await uploadBytes(storageRef, file);
    
    // Get the download URL
    const downloadURL = await getDownloadURL(snapshot.ref);
    
    return downloadURL;
  } catch (error) {
    console.error('Error uploading image to Firebase Storage:', error);
    throw new Error('Failed to upload image. Please try again.');
  }
}

/**
 * Upload a recipe image thumbnail Blob to Firebase Storage.
 * Thumbnails are stored under the `thumbnails/` prefix with a unique filename.
 *
 * @param {Blob} thumbnailBlob - The thumbnail Blob (typically JPEG).
 * @returns {Promise<string>} Download URL of the uploaded thumbnail.
 */
export async function uploadRecipeThumbnail(thumbnailBlob) {
  if (!thumbnailBlob) {
    throw new Error('No thumbnail blob provided');
  }

  try {
    const timestamp = Date.now();
    const randomStr = Math.random().toString(36).substring(2, 15);
    const filename = `recipe-thumb-${timestamp}-${randomStr}.jpg`;
    const storageRef = ref(storage, `thumbnails/${filename}`);

    const snapshot = await uploadBytes(storageRef, thumbnailBlob, {
      contentType: 'image/jpeg',
      cacheControl: 'public, max-age=31536000',
    });

    const downloadURL = await getDownloadURL(snapshot.ref);
    return downloadURL;
  } catch (error) {
    console.error('Error uploading recipe thumbnail to Firebase Storage:', error);
    throw new Error('Failed to upload thumbnail. Please try again.');
  }
}

/**
 * Delete a WhatsApp thumbnail from Firebase Storage.
 * Handles both firebasestorage.googleapis.com and storage.googleapis.com URLs,
 * since Cloud Functions generate thumbnails with public storage.googleapis.com URLs.
 * Errors are logged but not re-thrown so that thumbnail removal never blocks saving.
 *
 * @param {string} thumbnailUrl - The URL of the thumbnail to delete
 * @returns {Promise<void>}
 */
export async function deleteRecipeThumbnail(thumbnailUrl) {
  if (!thumbnailUrl) return;

  try {
    const url = new URL(thumbnailUrl);

    if (url.hostname === 'firebasestorage.googleapis.com') {
      // Standard Firebase Storage download URL
      const pathMatch = url.pathname.match(/\/o\/(.+)/);
      if (!pathMatch || !pathMatch[1]) {
        console.warn('[deleteRecipeThumbnail] Could not extract path from URL:', thumbnailUrl);
        return;
      }
      const path = decodeURIComponent(pathMatch[1].split('?')[0]);
      const storageRef = ref(storage, path);
      await deleteObject(storageRef);
    } else if (url.hostname === 'storage.googleapis.com') {
      // Public URL generated by Cloud Functions: https://storage.googleapis.com/{bucket}/{path}
      const parts = url.pathname.slice(1).split('/');
      // parts[0] is the bucket name; the rest is the file path inside the bucket
      const filePath = parts.slice(1).join('/');
      if (!filePath) {
        console.warn('[deleteRecipeThumbnail] Could not extract file path from URL:', thumbnailUrl);
        return;
      }
      const storageRef = ref(storage, filePath);
      await deleteObject(storageRef);
    } else {
      console.warn('[deleteRecipeThumbnail] Unrecognized thumbnail URL format:', thumbnailUrl);
    }
  } catch (error) {
    console.warn('[deleteRecipeThumbnail] Failed to delete thumbnail from Storage:', error);
  }
}

/**
 * Delete a recipe image from Firebase Storage
 * @param {string} imageUrl - The download URL or path of the image to delete
 * @returns {Promise<void>}
 */
export async function deleteRecipeImage(imageUrl) {
  if (!imageUrl || !isStorageUrl(imageUrl)) {
    // Not a Firebase Storage URL, nothing to delete
    return;
  }

  try {
    // Extract the path from the download URL
    // Firebase Storage URLs format: https://firebasestorage.googleapis.com/v0/b/{bucket}/o/{path}?alt=media...
    const url = new URL(imageUrl);
    // url.pathname doesn't include query params, so we safely extract just the path
    const pathMatch = url.pathname.match(/\/o\/(.+)/);
    
    if (!pathMatch || !pathMatch[1]) {
      console.warn('Could not extract path from Storage URL:', imageUrl);
      return;
    }
    
    // Decode the path (it's URL encoded in the download URL)
    const encodedPath = pathMatch[1];
    const path = decodeURIComponent(encodedPath);
    
    // Create a reference and delete
    const storageRef = ref(storage, path);
    await deleteObject(storageRef);
  } catch (error) {
    // Log the error but don't throw - deletion failures shouldn't block the app
    console.error('Error deleting image from Firebase Storage:', error);
  }
}

/** Fixed Storage path for the app logo used in social-media share previews. */
const APP_LOGO_STORAGE_PATH = 'settings/appLogo.png';

/**
 * Upload the app logo (as a Base64 data-URL) to Firebase Storage at a fixed
 * path so that social-media crawlers can access it via a public HTTPS URL.
 *
 * @param {string} base64Image - Base64 data-URL of the image (e.g. "data:image/png;base64,…")
 * @returns {Promise<string>} Public download URL
 */
export async function uploadAppLogoToStorage(base64Image) {
  if (!base64Image) {
    throw new Error('No image provided');
  }

  try {
    // Convert the data-URL to a Blob for upload
    const response = await fetch(base64Image);
    const blob = await response.blob();

    const storageRef = ref(storage, APP_LOGO_STORAGE_PATH);
    const snapshot = await uploadBytes(storageRef, blob, {
      contentType: blob.type || 'image/png',
      cacheControl: 'public, max-age=86400',
    });

    const downloadURL = await getDownloadURL(snapshot.ref);
    return downloadURL;
  } catch (error) {
    console.error('Error uploading app logo to Firebase Storage:', error);
    throw new Error('Failed to upload app logo. Please try again.');
  }
}

/**
 * Delete the app logo from Firebase Storage.
 * Errors are logged but not re-thrown so that logo removal never blocks saving.
 *
 * @returns {Promise<void>}
 */
export async function deleteAppLogoFromStorage() {
  try {
    const storageRef = ref(storage, APP_LOGO_STORAGE_PATH);
    await deleteObject(storageRef);
  } catch (error) {
    // The file might not exist yet – that's fine.
    console.warn('Could not delete app logo from Storage:', error);
  }
}

/**
 * Upload a menu grid image (Base64 data-URL) to Firebase Storage.
 *
 * @param {string} base64Image - Base64 data-URL of the grid image
 * @param {string} menuId - Menu ID for the filename
 * @returns {Promise<string>} Public download URL
 */
export async function uploadMenuGridImage(base64Image, menuId) {
  if (!base64Image || !menuId) {
    throw new Error('No image or menu ID provided');
  }

  try {
    // Convert the data-URL to a Blob for upload
    const response = await fetch(base64Image);
    const blob = await response.blob();

    // Generate filename: recipes/menu-grid-{menuId}.jpg
    const filename = `menu-grid-${menuId}.jpg`;
    const storageRef = ref(storage, `recipes/${filename}`);

    const snapshot = await uploadBytes(storageRef, blob, {
      contentType: 'image/jpeg',
      cacheControl: 'public, max-age=86400',
    });

    const downloadURL = await getDownloadURL(snapshot.ref);
    return downloadURL;
  } catch (error) {
    console.error('Error uploading menu grid image to Firebase Storage:', error);
    throw new Error('Failed to upload menu grid image. Please try again.');
  }
}

/**
 * Delete a menu grid image from Firebase Storage.
 * Errors are logged but not re-thrown so that deletion never blocks saving.
 *
 * @param {string} imageUrl - The download URL of the grid image to delete
 * @returns {Promise<void>}
 */
export async function deleteMenuGridImage(imageUrl) {
  if (!imageUrl || !isStorageUrl(imageUrl)) {
    return;
  }

  try {
    const url = new URL(imageUrl);
    const pathMatch = url.pathname.match(/\/o\/(.+)/);

    if (!pathMatch || !pathMatch[1]) {
      console.warn('Could not extract path from Storage URL:', imageUrl);
      return;
    }

    const encodedPath = pathMatch[1];
    const path = decodeURIComponent(encodedPath);

    const storageRef = ref(storage, path);
    await deleteObject(storageRef);
    console.log('[deleteMenuGridImage] Deleted old grid image:', path);
  } catch (error) {
    console.error('Error deleting menu grid image from Firebase Storage:', error);
  }
}

/**
 * Check if a URL is a Firebase Storage URL
 * @param {string} imageUrl - The URL to check
 * @returns {boolean} - True if it's a Firebase Storage URL
 */
export function isStorageUrl(imageUrl) {
  if (!imageUrl || typeof imageUrl !== 'string') {
    return false;
  }
  
  try {
    // Parse the URL and check if hostname matches Firebase Storage
    const url = new URL(imageUrl);
    return url.hostname === 'firebasestorage.googleapis.com';
  } catch {
    // Invalid URL
    return false;
  }
}
